app_settings:
  log_file_path: !!str "./log/logfile.log"
  host: !!str "0.0.0.0"
  port: !!int 8080
driver_params:
  driver_type: !!str "chrome"
  driver_path: !!str "./chromedriver"
  timeout: !!int 60
validator_params:
  verification_link: !!str "https://google.com"
  timeout: !!int 30